# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\misimportaciones\src\ui\dlgarticulo.ui'
#
# Created: Sat Sep 03 19:34:28 2011
#      by: PyQt4 UI code generator 4.7.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_dlgArticulo(object):
    def setupUi(self, dlgArticulo):
        dlgArticulo.setObjectName(_fromUtf8("dlgArticulo"))
        dlgArticulo.resize(555, 293)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dlgArticulo.sizePolicy().hasHeightForWidth())
        dlgArticulo.setSizePolicy(sizePolicy)
        dlgArticulo.setMinimumSize(QtCore.QSize(500, 250))
        dlgArticulo.setMaximumSize(QtCore.QSize(1000, 1000))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(dlgArticulo)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox = QtGui.QGroupBox(dlgArticulo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.categoriesview = TreeOfTableWidget(self.groupBox)
        self.categoriesview.setObjectName(_fromUtf8("categoriesview"))
        self.verticalLayout.addWidget(self.categoriesview)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_9.addWidget(self.label_13)
        self.txtCategorySearch = QtGui.QLineEdit(self.groupBox)
        self.txtCategorySearch.setObjectName(_fromUtf8("txtCategorySearch"))
        self.horizontalLayout_9.addWidget(self.txtCategorySearch)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(dlgArticulo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txtcategoria = QtGui.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.txtcategoria.setFont(font)
        self.txtcategoria.setAlignment(QtCore.Qt.AlignCenter)
        self.txtcategoria.setReadOnly(True)
        self.txtcategoria.setObjectName(_fromUtf8("txtcategoria"))
        self.gridLayout.addWidget(self.txtcategoria, 0, 1, 1, 3)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.txtmarca = QtGui.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.txtmarca.setFont(font)
        self.txtmarca.setAlignment(QtCore.Qt.AlignCenter)
        self.txtmarca.setReadOnly(True)
        self.txtmarca.setObjectName(_fromUtf8("txtmarca"))
        self.gridLayout.addWidget(self.txtmarca, 1, 1, 1, 3)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 3)
        self.txtunidades = QtGui.QSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.txtunidades.setFont(font)
        self.txtunidades.setAlignment(QtCore.Qt.AlignCenter)
        self.txtunidades.setObjectName(_fromUtf8("txtunidades"))
        self.gridLayout.addWidget(self.txtunidades, 4, 0, 1, 4)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 3)
        self.txtprecio = QtGui.QDoubleSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.txtprecio.setFont(font)
        self.txtprecio.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtprecio.setProperty(_fromUtf8("value"), 99.99)
        self.txtprecio.setObjectName(_fromUtf8("txtprecio"))
        self.gridLayout.addWidget(self.txtprecio, 6, 0, 1, 4)
        self.btnguardar = QtGui.QPushButton(self.groupBox_2)
        self.btnguardar.setAutoDefault(False)
        self.btnguardar.setObjectName(_fromUtf8("btnguardar"))
        self.gridLayout.addWidget(self.btnguardar, 7, 0, 1, 2)
        self.ckunit = QtGui.QCheckBox(self.groupBox_2)
        self.ckunit.setChecked(False)
        self.ckunit.setObjectName(_fromUtf8("ckunit"))
        self.gridLayout.addWidget(self.ckunit, 3, 3, 1, 1)
        self.ckprecio = QtGui.QCheckBox(self.groupBox_2)
        self.ckprecio.setObjectName(_fromUtf8("ckprecio"))
        self.gridLayout.addWidget(self.ckprecio, 5, 3, 1, 1)
        self.btncancelar = QtGui.QPushButton(self.groupBox_2)
        self.btncancelar.setAutoDefault(False)
        self.btncancelar.setObjectName(_fromUtf8("btncancelar"))
        self.gridLayout.addWidget(self.btncancelar, 7, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.label_13.setBuddy(self.txtCategorySearch)

        self.retranslateUi(dlgArticulo)
        QtCore.QMetaObject.connectSlotsByName(dlgArticulo)
        dlgArticulo.setTabOrder(self.txtunidades, self.txtprecio)
        dlgArticulo.setTabOrder(self.txtprecio, self.txtcategoria)
        dlgArticulo.setTabOrder(self.txtcategoria, self.txtmarca)
        dlgArticulo.setTabOrder(self.txtmarca, self.categoriesview)
        dlgArticulo.setTabOrder(self.categoriesview, self.txtCategorySearch)
        dlgArticulo.setTabOrder(self.txtCategorySearch, self.btnguardar)
        dlgArticulo.setTabOrder(self.btnguardar, self.ckunit)
        dlgArticulo.setTabOrder(self.ckunit, self.ckprecio)
        dlgArticulo.setTabOrder(self.ckprecio, self.btncancelar)

    def retranslateUi(self, dlgArticulo):
        dlgArticulo.setWindowTitle(QtGui.QApplication.translate("dlgArticulo", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("dlgArticulo", "Productos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("dlgArticulo", "Buscar", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("dlgArticulo", "Datos del Articulo", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("dlgArticulo", "Articulo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("dlgArticulo", "Marca", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("dlgArticulo", "Unidades por caja", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("dlgArticulo", "Precio Nuevo", None, QtGui.QApplication.UnicodeUTF8))
        self.txtprecio.setPrefix(QtGui.QApplication.translate("dlgArticulo", "C$ ", None, QtGui.QApplication.UnicodeUTF8))
        self.btnguardar.setText(QtGui.QApplication.translate("dlgArticulo", "Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.ckunit.setText(QtGui.QApplication.translate("dlgArticulo", "Copiar", None, QtGui.QApplication.UnicodeUTF8))
        self.ckprecio.setText(QtGui.QApplication.translate("dlgArticulo", "Copiar", None, QtGui.QApplication.UnicodeUTF8))
        self.btncancelar.setText(QtGui.QApplication.translate("dlgArticulo", "Cancelar", None, QtGui.QApplication.UnicodeUTF8))
        self.btncancelar.setShortcut(QtGui.QApplication.translate("dlgArticulo", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))

from factura.treewidget import TreeOfTableWidget
import res_rc
