# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\workspace\EsquipulasPy\esquipulaspy\ui\dlgmovimientosbancarios.ui'
#
# Created: Mon May 09 00:08:21 2011
#      by: PyQt4 UI code generator 4.7.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_dlgMovimientosBancarios(object):
    def setupUi(self, dlgMovimientosBancarios):
        dlgMovimientosBancarios.setObjectName(_fromUtf8("dlgMovimientosBancarios"))
        dlgMovimientosBancarios.resize(499, 340)
        dlgMovimientosBancarios.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dlgMovimientosBancarios.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(dlgMovimientosBancarios)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.label_25 = QtGui.QLabel(dlgMovimientosBancarios)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_31.addWidget(self.label_25)
        self.cbtipodoc = QtGui.QComboBox(dlgMovimientosBancarios)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbtipodoc.sizePolicy().hasHeightForWidth())
        self.cbtipodoc.setSizePolicy(sizePolicy)
        self.cbtipodoc.setEditable(True)
        self.cbtipodoc.setObjectName(_fromUtf8("cbtipodoc"))
        self.horizontalLayout_31.addWidget(self.cbtipodoc)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_31)
        self.label_26 = QtGui.QLabel(dlgMovimientosBancarios)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_30.addWidget(self.label_26)
        self.dtPicker = QtGui.QDateTimeEdit(dlgMovimientosBancarios)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtPicker.sizePolicy().hasHeightForWidth())
        self.dtPicker.setSizePolicy(sizePolicy)
        self.dtPicker.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dtPicker.setReadOnly(False)
        self.dtPicker.setCalendarPopup(True)
        self.dtPicker.setObjectName(_fromUtf8("dtPicker"))
        self.horizontalLayout_30.addWidget(self.dtPicker)
        self.gridLayout.addLayout(self.horizontalLayout_30, 0, 0, 1, 1)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_23 = QtGui.QLabel(dlgMovimientosBancarios)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_28.addWidget(self.label_23)
        self.cbconcepto = QtGui.QComboBox(dlgMovimientosBancarios)
        self.cbconcepto.setMinimumSize(QtCore.QSize(0, 20))
        self.cbconcepto.setEditable(True)
        self.cbconcepto.setObjectName(_fromUtf8("cbconcepto"))
        self.horizontalLayout_28.addWidget(self.cbconcepto)
        self.gridLayout.addLayout(self.horizontalLayout_28, 1, 0, 1, 1)
        self.label_22 = QtGui.QLabel(dlgMovimientosBancarios)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout.addWidget(self.label_22, 2, 0, 1, 1)
        self.splitter_4 = QtGui.QSplitter(dlgMovimientosBancarios)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.tabledetails = QtGui.QTableView(self.splitter_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabledetails.sizePolicy().hasHeightForWidth())
        self.tabledetails.setSizePolicy(sizePolicy)
        self.tabledetails.setMinimumSize(QtCore.QSize(300, 150))
        self.tabledetails.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabledetails.setObjectName(_fromUtf8("tabledetails"))
        self.layoutWidget_17 = QtGui.QWidget(self.splitter_4)
        self.layoutWidget_17.setObjectName(_fromUtf8("layoutWidget_17"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.layoutWidget_17)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_24 = QtGui.QLabel(self.layoutWidget_17)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.verticalLayout_13.addWidget(self.label_24)
        self.txtobservaciones = QtGui.QTextEdit(self.layoutWidget_17)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtobservaciones.sizePolicy().hasHeightForWidth())
        self.txtobservaciones.setSizePolicy(sizePolicy)
        self.txtobservaciones.setMinimumSize(QtCore.QSize(0, 40))
        self.txtobservaciones.setObjectName(_fromUtf8("txtobservaciones"))
        self.verticalLayout_13.addWidget(self.txtobservaciones)
        self.gridLayout.addWidget(self.splitter_4, 3, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(dlgMovimientosBancarios)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 1)
        self.label_26.setBuddy(self.dtPicker)

        self.retranslateUi(dlgMovimientosBancarios)
        self.cbtipodoc.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(dlgMovimientosBancarios)

    def retranslateUi(self, dlgMovimientosBancarios):
        dlgMovimientosBancarios.setWindowTitle(QtGui.QApplication.translate("dlgMovimientosBancarios", "Notas de Credito o Debito", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("dlgMovimientosBancarios", "Tipo de Doc.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("dlgMovimientosBancarios", "Fecha", None, QtGui.QApplication.UnicodeUTF8))
        self.dtPicker.setDisplayFormat(QtGui.QApplication.translate("dlgMovimientosBancarios", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("dlgMovimientosBancarios", "En concepto de:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("dlgMovimientosBancarios", "Cuentas que afecta", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("dlgMovimientosBancarios", "Observaciones", None, QtGui.QApplication.UnicodeUTF8))

import res_rc
