# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\workspace\misimportaciones\src\ui\factura.ui'
#
# Created: Mon Aug 22 19:00:47 2011
#      by: PyQt4 UI code generator 4.7.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_frmFactura(object):
    def setupUi(self, frmFactura):
        frmFactura.setObjectName(_fromUtf8("frmFactura"))
        frmFactura.resize(918, 631)
        self.centralwidget = QtGui.QWidget(frmFactura)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabdetails = QtGui.QWidget()
        self.tabdetails.setObjectName(_fromUtf8("tabdetails"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabdetails)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_5 = QtGui.QLabel(self.tabdetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.dtPicker = QtGui.QDateTimeEdit(self.tabdetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtPicker.sizePolicy().hasHeightForWidth())
        self.dtPicker.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dtPicker.setFont(font)
        self.dtPicker.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dtPicker.setReadOnly(False)
        self.dtPicker.setCalendarPopup(True)
        self.dtPicker.setObjectName(_fromUtf8("dtPicker"))
        self.gridLayout.addWidget(self.dtPicker, 0, 3, 1, 1)
        self.label = QtGui.QLabel(self.tabdetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 4, 1, 1)
        self.swcliente = QtGui.QStackedWidget(self.tabdetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swcliente.sizePolicy().hasHeightForWidth())
        self.swcliente.setSizePolicy(sizePolicy)
        self.swcliente.setObjectName(_fromUtf8("swcliente"))
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.page_3)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.cbcliente = QtGui.QComboBox(self.page_3)
        self.cbcliente.setEditable(True)
        self.cbcliente.setObjectName(_fromUtf8("cbcliente"))
        self.horizontalLayout_4.addWidget(self.cbcliente)
        self.swcliente.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.page_4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.txtcliente = QtGui.QLineEdit(self.page_4)
        self.txtcliente.setReadOnly(True)
        self.txtcliente.setObjectName(_fromUtf8("txtcliente"))
        self.horizontalLayout_3.addWidget(self.txtcliente)
        self.swcliente.addWidget(self.page_4)
        self.gridLayout.addWidget(self.swcliente, 0, 5, 1, 2)
        self.label_6 = QtGui.QLabel(self.tabdetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.lblnumero = QtGui.QLabel(self.tabdetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblnumero.sizePolicy().hasHeightForWidth())
        self.lblnumero.setSizePolicy(sizePolicy)
        self.lblnumero.setObjectName(_fromUtf8("lblnumero"))
        self.gridLayout.addWidget(self.lblnumero, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.splitter = QtGui.QSplitter(self.tabdetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.groupBox = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.categoriesview = TreeOfTableWidget(self.groupBox)
        self.categoriesview.setObjectName(_fromUtf8("categoriesview"))
        self.verticalLayout.addWidget(self.categoriesview)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_9.addWidget(self.label_13)
        self.txtCategorySearch = QtGui.QLineEdit(self.groupBox)
        self.txtCategorySearch.setObjectName(_fromUtf8("txtCategorySearch"))
        self.horizontalLayout_9.addWidget(self.txtCategorySearch)
        self.btneditar = QtGui.QPushButton(self.groupBox)
        self.btneditar.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/document-edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btneditar.setIcon(icon)
        self.btneditar.setObjectName(_fromUtf8("btneditar"))
        self.horizontalLayout_9.addWidget(self.btneditar)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.groupBox_2 = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabledetails = OrderedEditTable(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabledetails.sizePolicy().hasHeightForWidth())
        self.tabledetails.setSizePolicy(sizePolicy)
        self.tabledetails.setMinimumSize(QtCore.QSize(0, 100))
        self.tabledetails.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tabledetails.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabledetails.setAlternatingRowColors(True)
        self.tabledetails.setObjectName(_fromUtf8("tabledetails"))
        self.verticalLayout_3.addWidget(self.tabledetails)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_6.addWidget(self.label_9)
        self.lbltotal = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbltotal.sizePolicy().hasHeightForWidth())
        self.lbltotal.setSizePolicy(sizePolicy)
        self.lbltotal.setMinimumSize(QtCore.QSize(60, 0))
        self.lbltotal.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.lbltotal.setFont(font)
        self.lbltotal.setStyleSheet(_fromUtf8(""))
        self.lbltotal.setText(_fromUtf8(""))
        self.lbltotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbltotal.setObjectName(_fromUtf8("lbltotal"))
        self.horizontalLayout_6.addWidget(self.lbltotal)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.txtobservaciones = QtGui.QPlainTextEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtobservaciones.sizePolicy().hasHeightForWidth())
        self.txtobservaciones.setSizePolicy(sizePolicy)
        self.txtobservaciones.setMinimumSize(QtCore.QSize(0, 40))
        self.txtobservaciones.setMaximumSize(QtCore.QSize(16777215, 80))
        self.txtobservaciones.setReadOnly(True)
        self.txtobservaciones.setObjectName(_fromUtf8("txtobservaciones"))
        self.gridLayout_2.addWidget(self.txtobservaciones, 1, 0, 2, 2)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout_4.addWidget(self.splitter)
        self.tabWidget.addTab(self.tabdetails, icon, _fromUtf8(""))
        self.tabnavigation = QtGui.QWidget()
        self.tabnavigation.setObjectName(_fromUtf8("tabnavigation"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabnavigation)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tablenavigation = QtGui.QTableView(self.tabnavigation)
        self.tablenavigation.setAlternatingRowColors(True)
        self.tablenavigation.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tablenavigation.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tablenavigation.setObjectName(_fromUtf8("tablenavigation"))
        self.tablenavigation.horizontalHeader().setStretchLastSection(True)
        self.tablenavigation.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tablenavigation)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.tabnavigation)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.txtSearch = QtGui.QLineEdit(self.tabnavigation)
        self.txtSearch.setObjectName(_fromUtf8("txtSearch"))
        self.horizontalLayout.addWidget(self.txtSearch)
        self.cboFiltro = QtGui.QComboBox(self.tabnavigation)
        self.cboFiltro.setObjectName(_fromUtf8("cboFiltro"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/res/simbolo-dolar-300x245.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cboFiltro.addItem(icon1, _fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/checkbox.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cboFiltro.addItem(icon2, _fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/edit-delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cboFiltro.addItem(icon3, _fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/res/account-types-checking.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cboFiltro.addItem(icon4, _fromUtf8(""))
        self.cboFiltro.addItem(icon, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.cboFiltro)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/res/table.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabnavigation, icon5, _fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.tabWidget)
#        frmFactura.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(frmFactura)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
#        frmFactura.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(frmFactura)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
#        frmFactura.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.actionAnular = QtGui.QAction(frmFactura)
        self.actionAnular.setEnabled(True)
        self.actionAnular.setIcon(icon3)
        self.actionAnular.setObjectName(_fromUtf8("actionAnular"))
        self.actionEditar = QtGui.QAction(frmFactura)
        self.actionEditar.setIcon(icon)
        self.actionEditar.setObjectName(_fromUtf8("actionEditar"))
        self.toolBar.addAction(self.actionAnular)
        self.label_5.setBuddy(self.dtPicker)
        self.label.setBuddy(self.txtcliente)
        self.label_6.setBuddy(self.dtPicker)
        self.lblnumero.setBuddy(self.dtPicker)
        self.label_13.setBuddy(self.txtCategorySearch)
        self.label_4.setBuddy(self.txtSearch)

        self.retranslateUi(frmFactura)
        self.tabWidget.setCurrentIndex(0)
        self.swcliente.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmFactura)
        frmFactura.setTabOrder(self.cbcliente, self.txtobservaciones)
        frmFactura.setTabOrder(self.txtobservaciones, self.txtSearch)
        frmFactura.setTabOrder(self.txtSearch, self.tablenavigation)

    def retranslateUi(self, frmFactura):
        frmFactura.setWindowTitle(QtGui.QApplication.translate("frmFactura", "Factura", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("frmFactura", "<b>Fecha</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.dtPicker.setDisplayFormat(QtGui.QApplication.translate("frmFactura", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("frmFactura", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">&amp;Nlombre del Cliente</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("frmFactura", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Factura No.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblnumero.setText(QtGui.QApplication.translate("frmFactura", "xxx", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("frmFactura", "Productos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("frmFactura", "Buscar", None, QtGui.QApplication.UnicodeUTF8))
        self.btneditar.setToolTip(QtGui.QApplication.translate("frmFactura", "Editar Producto", None, QtGui.QApplication.UnicodeUTF8))
        self.btneditar.setShortcut(QtGui.QApplication.translate("frmFactura", "Ctrl+F2", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("frmFactura", "Detalle de la factura", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("frmFactura", "<b>Total</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("frmFactura", "<b>Observaciones</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabdetails), '')
        self.label_4.setText(QtGui.QApplication.translate("frmFactura", "&Buscar", None, QtGui.QApplication.UnicodeUTF8))
        self.cboFiltro.setItemText(0, QtGui.QApplication.translate("frmFactura", "Todas", None, QtGui.QApplication.UnicodeUTF8))
        self.cboFiltro.setItemText(1, QtGui.QApplication.translate("frmFactura", "Confirmadas", None, QtGui.QApplication.UnicodeUTF8))
        self.cboFiltro.setItemText(2, QtGui.QApplication.translate("frmFactura", "Anuladas", None, QtGui.QApplication.UnicodeUTF8))
        self.cboFiltro.setItemText(3, QtGui.QApplication.translate("frmFactura", "Crédito Pendiente", None, QtGui.QApplication.UnicodeUTF8))
        self.cboFiltro.setItemText(4, QtGui.QApplication.translate("frmFactura", "Anulación pendiente", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabnavigation), '')
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("frmFactura", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAnular.setText(QtGui.QApplication.translate("frmFactura", "anular", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAnular.setToolTip(QtGui.QApplication.translate("frmFactura", "Anular la Factura", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditar.setText(QtGui.QApplication.translate("frmFactura", "Editar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditar.setToolTip(QtGui.QApplication.translate("frmFactura", "Editar", None, QtGui.QApplication.UnicodeUTF8))

from herramientas.widgets import OrderedEditTable
from factura.treewidget import TreeOfTableWidget
import res_rc
